// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjvbvexccxbpwhftijlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqdmJ2ZXhjY3hicHdoZnRpamxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDA5MTMsImV4cCI6MjA2NDIxNjkxM30.Dvp5YwPoCyEswAGHwBXEqkdOp_2Z5doiOGjkuvVnQVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);